import './globals.css';
import Scaffold from "@/components/scaffold/Scaffold"

export const metadata = {
  title: 'Shorthand',
  description: 'Generated by LucasGarcia',
}

export default function RootLayout({ children }: { children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <Scaffold></Scaffold>                
      </body>
    </html>
  )
}
